import os

WHEEL_CONTROLER_DATA_ROOT = os.path.join('.', 'data', 'wheelcontroller')
WHEEL_CONTROLER_VALIDATION_DATA_ROOT = os.path.join(WHEEL_CONTROLER_DATA_ROOT, "validationimages")
WHEEL_CONTROLER_TEST_DATA_ROOT = os.path.join(WHEEL_CONTROLER_DATA_ROOT, "testimages")
WHEEL_CONTROLER_IMAGES_ROOT = os.path.join(WHEEL_CONTROLER_DATA_ROOT, "images")
WHEEL_CONTROLER_WEIGHTS_ROOT = os.path.join(WHEEL_CONTROLER_DATA_ROOT, "weights")

BRAKE_DATA_ROOT = os.path.join('.', 'data', 'brake')
BRAKE_VALIDATION_DATA_ROOT = os.path.join(BRAKE_DATA_ROOT, "validationimages")
BRAKE_TEST_DATA_ROOT = os.path.join(BRAKE_DATA_ROOT, "testimages")
BRAKE_IMAGES_ROOT = os.path.join(BRAKE_DATA_ROOT, 'images')
BRAKE_WEIGHTS_ROOT = os.path.join(BRAKE_DATA_ROOT, 'weights')

# TRAIN_DATA_PATH = WHEEL_CONTROLER_IMAGES_ROOT
# VALIDATION_DATA_PATH = WHEEL_CONTROLER_VALIDATION_DATA_ROOT
# TEST_DATA_PATH = WHEEL_CONTROLER_TEST_DATA_ROOT

TRAIN_DATA_PATH = BRAKE_IMAGES_ROOT
VALIDATION_DATA_PATH = BRAKE_VALIDATION_DATA_ROOT
TEST_DATA_PATH = BRAKE_TEST_DATA_ROOT